backend:
  name: nectoj.io
  branch: Senpai

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', }
      - { label: 'Publish Date', name: 'publishdate', widget: 'datetime' }
      - { label: 'SEO Description', name: 'seoDescription', widget: 'string', required: false }
      - { label: 'Content', name: 'content', widget: 'markdown', required: true }
      - { label: 'Tags', name: 'tags', widget: 'string', required: false }
      - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }
  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "tags"
        label: "Tags"
        file: "content/tags.yml"
        description: "Contains list of tags"
        fields:
          - label: "Slug"
            name: "slug"
            widget: "string"
            hint: "The part of the URL that identifies the tag"
          - label: "Display Name"
            name: "name"
            widget: "string"
            hint: "Tag name for displaying on the site"